### ISSUE TITLE
Project Proposal feedback from IB 599 classmates

### ISSUE THREAD

**Issue by jwongala** [jwongala/Lagrangian-particle-tracking-model#1]

**Comment by Juniper41** [comment]
I liked your visuals a lot, they helped explain your research well. Having modularized and reproducible code is a great term goal to have and I think very attainable and beneficial down the road.

**Comment by zechmeunier** [comment]
You have a very interesting, integrative project! Are you tracking commercially important species?

**Comment by Coffee-Powered-Scientist** [comment]
Nice use of animations, unfortunate that it didn't work well with discord.

**Comment by Angelika-Kurthen** [comment]
Hi Jennifer!

I thought the inclusion of the animation was such an engaging idea and gave me a good idea about what you were doing, without needing too much background information. I also totally sympathize with what you said about not feeling comfortable sharing your code with others because it isn't modular enough - I feel the exact same way!

**Comment by McLeodMJ** [comment]
Hi Jennifer, very cool animation! Thank you for describing the Lagrangian model, I am entirely unfamiliar, but it is a unique method and I know I would value seeing a reproducible product.

**Comment by howardre** [comment]
You did a great job of presenting this even without the ability to use the animations!

**Comment by jessealaney** [comment]
Jennifer, I share some of your "bad habits" in terms of coding. I've found that commenting my code thoroughly helps keep me sane. Reproducible metric calculations sounds like a good idea. Very interesting project! I'd love to hear more.

**Comment by breshears-logan** [comment]
Good job presenting regardless of the animation not functioning properly! I don't think I caught this, but what species of larval fish you are modeling?
