### ISSUE TITLE
Project report update - IB 599

### ISSUE THREAD

**Issue by jwongala** [jwongala/Lagrangian-particle-tracking-model#3]
Feedback from classmates

**Comment by Juniper41** [comment]
Analysis reproducibility is a huge step, glad that you noticed that and made it a priority, and I can 100% sympathise with the time management struggle. It seems like my deadlines are always slipping and I never have enough time in the week. Great job on your presentation, and workflow!

**Comment by Angelika-Kurthen** [comment]
I totally get the time management struggles! I also appreciate that you are constantly updating your goals. I feel like sometimes I forget to take time to reflect and reevaluate what needs to be done and what is doable.

**Comment by howardre** [comment]
I thought it was great that you highlighted how difficult it is to make the analyses reproducible, because I definitely feel like that can be way more difficult and time consuming than you initially think it will be

**Comment by Coffee-Powered-Scientist** [comment]
Good work, I would suggest not getting too far behind on commits-I have branches that are completely different because of indecisive branch management.

**Comment by McLeodMJ** [comment]
Hi Jennifer! Great job getting your model more modularized, that will really pay off in the long run.

**Comment by jessealaney** [comment]
The schematic you provided was really helpful in terms of me understanding your project! Looks like you're making good project. I hear you about time management too!

**Comment by zechmeunier** [comment]
Making all your code reproduceable and understandable by someone else is challenging. I need to improve that as well!
